### Importing the libraries:

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

### Loading the dataset:

In [2]:
header_list=['A1','A2','A3','A4','A5','A6','A7','A8','A9','A10','A11','A12','A13','A14','A15','A16']
df=pd.read_csv('crx.data',names=header_list)
pd.set_option('display.max_rows', 1000)
new_df=df.replace(to_replace ='?', value =np.nan)
new_df.head(10)

  A1     A2      A3 A4 A5  A6 A7     A8 A9 A10  A11 A12 A13    A14    A15 A16
0  b  30.83   0.000  u  g   w  v  1.250  t   t    1   f   g  00202      0   +
1  a  58.67   4.460  u  g   q  h  3.040  t   t    6   f   g  00043    560   +
2  a  24.50   0.500  u  g   q  h  1.500  t   f    0   f   g  00280    824   +
3  b  27.83   1.540  u  g   w  v  3.750  t   t    5   t   g  00100      3   +
4  b  20.17   5.625  u  g   w  v  1.710  t   f    0   f   s  00120      0   +
5  b  32.08   4.000  u  g   m  v  2.500  t   f    0   t   g  00360      0   +
6  b  33.17   1.040  u  g   r  h  6.500  t   f    0   t   g  00164  31285   +
7  a  22.92  11.585  u  g  cc  v  0.040  t   f    0   f   g  00080   1349   +
8  b  54.42   0.500  y  p   k  h  3.960  t   f    0   f   g  00180    314   +
9  b  42.50   4.915  y  p   w  v  3.165  t   f    0   t   g  00052   1442   +

### Checking for null values:

In [3]:
new_df.isnull()
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A1      678 non-null    object
 1   A2      678 non-null    object
 2   A3      690 non-null    float64
 3   A4      684 non-null    object
 4   A5      684 non-null    object
 5   A6      681 non-null    object
 6   A7      681 non-null    object
 7   A8      690 non-null    float64
 8   A9      690 non-null    object
 9   A10     690 non-null    object
 10  A11     690 non-null    int64
 11  A12     690 non-null    object
 12  A13     690 non-null    object
 13  A14     677 non-null    object
 14  A15     690 non-null    int64
 15  A16     690 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.4+ KB

In [5]:
new_df_1=new_df.dropna()

In [6]:
new_df_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 653 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A1      653 non-null    object
 1   A2      653 non-null    object
 2   A3      653 non-null    float64
 3   A4      653 non-null    object
 4   A5      653 non-null    object
 5   A6      653 non-null    object
 6   A7      653 non-null    object
 7   A8      653 non-null    float64
 8   A9      653 non-null    object
 9   A10     653 non-null    object
 10  A11     653 non-null    int64
 11  A12     653 non-null    object
 12  A13     653 non-null    object
 13  A14     653 non-null    object
 14  A15     653 non-null    int64
 15  A16     653 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.7+ KB

In [7]:
new_df_1.tail(10)

    A1     A2      A3 A4 A5  A6  A7     A8 A9 A10  A11 A12 A13    A14  A15 A16
680  b  19.50   0.290  u  g   k   v  0.290  f   f    0   f   g  00280  364   -
681  b  27.83   1.000  y  p   d   h  3.000  f   f    0   f   g  00176  537   -
682  b  17.08   3.290  u  g   i   v  0.335  f   f    0   t   g  00140    2   -
683  b  36.42   0.750  y  p   d   v  0.585  f   f    0   f   g  00240    3   -
684  b  40.58   3.290  u  g   m   v  3.500  f   f    0   t   s  00400    0   -
685  b  21.08  10.085  y  p   e   h  1.250  f   f    0   f   g  00260    0   -
686  a  22.67   0.750  u  g   c   v  2.000  f   t    2   t   g  00200  394   -
687  a  25.25  13.500  y  p  ff  ff  2.000  f   t    1   t   g  00200    1   -
688  b  17.92   0.205  u  g  aa   v  0.040  f   f    0   f   g  00280  750   -
689  b  35.00   3.375  u  g   c   h  8.290  f   f    0   t   g  00000    0   -

### Treating the categorical and continous features seperately:

In [9]:
new_df_ca=new_df_1[['A1','A4','A5','A6','A7','A9','A10','A12','A13']]

In [10]:
new_df_ca.head(10)

  A1 A4 A5  A6 A7 A9 A10 A12 A13
0  b  u  g   w  v  t   t   f   g
1  a  u  g   q  h  t   t   f   g
2  a  u  g   q  h  t   f   f   g
3  b  u  g   w  v  t   t   t   g
4  b  u  g   w  v  t   f   f   s
5  b  u  g   m  v  t   f   t   g
6  b  u  g   r  h  t   f   t   g
7  a  u  g  cc  v  t   f   f   g
8  b  y  p   k  h  t   f   f   g
9  b  y  p   w  v  t   f   t   g

In [11]:
new_df_cp=new_df_1[['A2','A3','A8','A11','A14','A15']]
new_df_cp["A2"] = pd.to_numeric(new_df_cp["A2"], downcast="float")
new_df_cp["A3"] = pd.to_numeric(new_df_cp["A3"], downcast="float")
new_df_cp["A8"] = pd.to_numeric(new_df_cp["A8"], downcast="float")
new_df_cp["A11"] = pd.to_numeric(new_df_cp["A11"], downcast="float")
new_df_cp["A14"] = pd.to_numeric(new_df_cp["A14"], downcast="float")
new_df_cp["A15"] = pd.to_numeric(new_df_cp["A15"], downcast="float")

/var/folders/9t/7_z6jytn219c403gvjz_jdfc0000gn/T/ipykernel_36099/1943675603.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df_cp["A2"] = pd.to_numeric(new_df_cp["A2"], downcast="float")
/var/folders/9t/7_z6jytn219c403gvjz_jdfc0000gn/T/ipykernel_36099/1943675603.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df_cp["A3"] = pd.to_numeric(new_df_cp["A3"], downcast="float")
/var/folders/9t/7_z6jytn219c403gvjz_jdfc0000gn/T/ipykernel_36099/1943675603.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df_cp["A8"] = pd.to_numeric(new_df_cp["A8"], downcast="float")
/var/folders/9t/7_z6jytn219c403gvjz_jdfc0000gn/T/ipykernel_36099/1943675603.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df_cp["A11"] = pd.to_numeric(new_df_cp["A11"], downcast="float")
/var/folders/9t/7_z6jytn219c403gvjz_jdfc0000gn/T/ipykernel_36099/1943675603.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df_cp["A14"] = pd.to_numeric(new_df_cp["A14"], downcast="float")
/var/folders/9t/7_z6jytn219c403gvjz_jdfc0000gn/T/ipykernel_36099/1943675603.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df_cp["A15"] = pd.to_numeric(new_df_cp["A15"], downcast="float")

In [12]:
new_df_cp.head(10)

          A2      A3     A8  A11    A14      A15
0  30.830000   0.000  1.250  1.0  202.0      0.0
1  58.669998   4.460  3.040  6.0   43.0    560.0
2  24.500000   0.500  1.500  0.0  280.0    824.0
3  27.830000   1.540  3.750  5.0  100.0      3.0
4  20.170000   5.625  1.710  0.0  120.0      0.0
5  32.080002   4.000  2.500  0.0  360.0      0.0
6  33.169998   1.040  6.500  0.0  164.0  31285.0
7  22.920000  11.585  0.040  0.0   80.0   1349.0
8  54.419998   0.500  3.960  0.0  180.0    314.0
9  42.500000   4.915  3.165  0.0   52.0   1442.0

In [13]:
new_df_target=new_df_1[['A16']]

In [14]:

value_dict={}
for col in new_df_ca.columns:
        unique_values=new_df_ca[col].unique()
        a=0
        if col not in value_dict:
            value_dict[col]={}
        
        for value in sorted(unique_values):
            new_df_ca[col].replace(value,a,inplace=True)
           
            if value not in value_dict[col]:
                value_dict[col][value]=a
            a+=1

/var/folders/9t/7_z6jytn219c403gvjz_jdfc0000gn/T/ipykernel_36099/3261803236.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df_ca[col].replace(value,a,inplace=True)

In [15]:
value_dict

{'A1': {'a': 0, 'b': 1},
 'A4': {'l': 0, 'u': 1, 'y': 2},
 'A5': {'g': 0, 'gg': 1, 'p': 2},
 'A6': {'aa': 0,
  'c': 1,
  'cc': 2,
  'd': 3,
  'e': 4,
  'ff': 5,
  'i': 6,
  'j': 7,
  'k': 8,
  'm': 9,
  'q': 10,
  'r': 11,
  'w': 12,
  'x': 13},
 'A7': {'bb': 0,
  'dd': 1,
  'ff': 2,
  'h': 3,
  'j': 4,
  'n': 5,
  'o': 6,
  'v': 7,
  'z': 8},
 'A9': {'f': 0, 't': 1},
 'A10': {'f': 0, 't': 1},
 'A12': {'f': 0, 't': 1},
 'A13': {'g': 0, 'p': 1, 's': 2}}

In [16]:
new_df_ca.head(10)

   A1  A4  A5  A6  A7  A9  A10  A12  A13
0   1   1   0  12   7   1    1    0    0
1   0   1   0  10   3   1    1    0    0
2   0   1   0  10   3   1    0    0    0
3   1   1   0  12   7   1    1    1    0
4   1   1   0  12   7   1    0    0    2
5   1   1   0   9   7   1    0    1    0
6   1   1   0  11   3   1    0    1    0
7   0   1   0   2   7   1    0    0    0
8   1   2   2   8   3   1    0    0    0
9   1   2   2  12   7   1    0    1    0

In [17]:
for column in new_df_cp.columns:
        new_df_cp[column] = (new_df_cp[column] - new_df_cp[column].mean()) / new_df_cp[column].std()

/var/folders/9t/7_z6jytn219c403gvjz_jdfc0000gn/T/ipykernel_36099/4153446176.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df_cp[column] = (new_df_cp[column] - new_df_cp[column].mean()) / new_df_cp[column].std()

In [18]:
new_df_cp.head(10)

         A2        A3        A8       A11       A14       A15
0 -0.056918 -0.960704 -0.294946 -0.302364  0.128583 -0.192977
1  2.294777 -0.073509  0.236036  0.703975 -0.816176 -0.086377
2 -0.591624 -0.861243 -0.220786 -0.503632  0.592050 -0.036122
3 -0.310333 -0.654363  0.446649  0.502707 -0.477489 -0.192406
4 -0.957387  0.158236 -0.158492 -0.503632 -0.358651 -0.192977
5  0.048672 -0.165013  0.075852 -0.503632  1.067400 -0.192977
6  0.140746 -0.753824  1.262403 -0.503632 -0.097208  5.762344
7 -0.725090  1.343816 -0.653877 -0.503632 -0.596327  0.063815
8  1.935771 -0.861243  0.508943 -0.503632 -0.002138 -0.133204
9  0.928868  0.017001  0.273116 -0.503632 -0.762699  0.081518

In [19]:
df_final=[new_df_ca,new_df_cp]
final=pd.concat(df_final,axis=1)

### Final DataFrame to be fed into the model:

In [20]:
final.head(20)

,A1,A4,A5,A6,A7,A9,A10,A12,A13,A2,A3,A8,A11,A14,A15
0,1,1,0,12,7,1,1,0,0,-0.056918,-0.960704,-0.294946,-0.302364,0.128583,-0.192977
1,0,1,0,10,3,1,1,0,0,2.294777,-0.073509,0.236036,0.703975,-0.816176,-0.086377
2,0,1,0,10,3,1,0,0,0,-0.591624,-0.861243,-0.220786,-0.503632,0.592050,-0.036122
3,1,1,0,12,7,1,1,1,0,-0.310333,-0.654363,0.446649,0.502707,-0.477489,-0.192406
4,1,1,0,12,7,1,0,0,2,-0.957387,0.158236,-0.158492,-0.503632,-0.358651,-0.192977
5,1,1,0,9,7,1,0,1,0,0.048672,-0.165013,0.075852,-0.503632,1.067400,-0.192977
6,1,1,0,11,3,1,0,1,0,0.140746,-0.753824,1.262403,-0.503632,-0.097208,5.762344
7,0,1,0,2,7,1,0,0,0,-0.725090,1.343816,-0.653877,-0.503632,-0.596327,0.063815
8,1,2,2,8,3,1,0,0,0,1.935771,-0.861243,0.508943,-0.503632,-0.002138,-0.133204
9,1,2,2,12,7,1,0,1,0,0.928868,0.017001,0.273116,-0.503632,-0.762699,0.081518
10,1,1,0,1,3,0,0,1,0,-0.796046,-0.795598,-0.023522,-0.503632,-0.311116,-0.192977
11,1,1,0,1,3,1,0,0,0,-0.133787,-0.595681,0.620182,-0.503632,0.473212,-0.154905
12,0,1,0,8,7,1,0,1,0,0.569863,0.232832,-0.369105,-0.503632,-1.071677,-0.192977
13,1,1,0,8,7,0,0,0,0,1.400221,0.240789,-0.653877,-0.503632,-1.071677,0.319084
14,0,1,0,10,7,1,1,1,0,1.210159,1.127984,0.817446,0.905242,-1.071677,-0.192977
15,1,2,2,8,7,1,1,1,0,0.436397,-0.082460,-0.591584,1.509046,0.829725,-0.192977
16,1,1,0,9,7,1,1,1,0,-0.274855,-0.786647,-0.380971,0.100172,1.281308,-0.192977
17,0,1,0,10,7,1,1,0,0,-0.697214,0.207967,0.274599,1.509046,-0.358651,-0.146339
18,1,1,0,3,3,1,0,1,0,-0.817164,-0.910973,-0.468479,-0.503632,-1.071677,-0.192977
19,0,1,0,2,3,1,1,0,0,-1.041859,0.747047,-0.443265,0.905242,-0.501256,-0.192977

In [21]:
unique_values=new_df_target['A16'].unique()
b=0
for value in sorted(unique_values):
    new_df_target['A16'].replace(value,b,inplace=True)
    b+=1

/var/folders/9t/7_z6jytn219c403gvjz_jdfc0000gn/T/ipykernel_36099/1904373495.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df_target['A16'].replace(value,b,inplace=True)

In [25]:
new_df_target

     A16
0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     0
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     1
72     1
73     1
74     1
75     1
76     1
77     1
78     1
79     1
80     1
81     1
82     1
84     1
85     1
87     1
88     1
89     1
90     1
91     1
93     1
94     1
95     1
96     1
98     1
99     1
100    1
101    1
102    1
103    1
104    1
105    1
106    1
107    1
108    1
109    1
110    1
111    1
112    1
113    1
114    1
115    1
116    1
117    0
118    0
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    0
139    0
140    0
141    0
142    0
143    0
144    0
145    0
146    0
147    0
148    0
149    0
150    0
151    0
152    0
153    0
154    0
155    0
156    0
157    0
158    0
159    0
160    0
161    0
162    0
163    0
164    0
165    0
166    0
167    0
168    0
169    0
170    0
171    0
172    0
173    0
174    0
175    0
176    0
177    0
178    0
179    0
180    0
181    0
182    0
183    0
184    0
185    0
186    0
187    0
188    0
189    0
190    0
191    0
192    0
193    0
194    0
195    0
196    0
197    0
198    0
199    0
200    0
201    0
203    0
204    0
205    0
207    0
208    0
209    0
210    0
211    0
212    0
213    0
214    0
215    0
216    0
217    0
218    0
219    0
220    0
221    0
222    0
223    0
224    0
225    0
226    0
227    0
228    0
229    0
230    0
231    0
232    0
233    0
234    0
235    0
236    0
237    0
238    0
239    0
240    0
241    0
242    0
244    0
245    0
246    0
247    0
249    0
250    0
251    0
252    0
253    0
255    1
256    1
257    1
258    1
259    1
260    1
261    1
262    1
263    1
264    1
265    1
266    1
267    1
268    0
269    0
271    1
272    1
273    1
274    1
275    1
276    1
277    1
279    1
280    1
281    1
282    1
283    1
284    1
285    1
287    1
288    1
289    1
290    1
291    1
292    1
293    1
294    1
295    1
296    1
297    1
298    1
299    1
300    1
301    1
302    1
303    1
304    1
305    1
306    1
307    1
308    1
309    1
310    1
311    1
312    1
313    1
314    1
315    1
316    1
317    0
318    0
319    0
320    0
321    0
322    0
323    0
324    1
325    1
326    1
328    1
331    1
332    1
333    1
334    1
335    1
336    1
337    1
338    1
339    1
340    1
341    1
342    1
343    1
344    1
345    1
347    1
348    1
349    1
350    1
351    1
352    1
353    1
354    1
355    1
356    1
357    1
358    1
359    1
360    1
361    1
362    1
363    1
364    1
365    1
366    1
367    1
368    1
369    1
370    1
371    1
372    1
373    1
375    1
376    1
377    1
378    1
379    1
380    1
381    1
382    1
383    1
384    1
385    1
386    1
387    1
388    1
389    1
390    1
391    1
392    1
393    1
394    1
395    1
396    1
397    1
398    1
399    1
400    1
401    1
402    1
403    1
404    1
405    1
407    1
408    1
409    1
410    1
411    1
412    1
413    1
414    1
415    1
416    1
417    1
418    1
419    1
420    1
421    1
422    1
423    1
424    1
425    1
426    1
427    1
428    1
429    1
430    1
431    1
432    1
433    1
434    1
435    1
436    1
437    1
438    1
439    1
440    1
441    1
442    1
443    1
444    1
446    1
447    1
448    1
449    1
451    1
452    1
454    1
455    1
457    1
458    1
459    1
460    1
461    1
462    1
463    1
464    1
465    1
466    1
467    1
468    1
469    1
470    1
471    1
472    1
473    1
474    1
475    1
476    1
477    1
478    1
480    1
481    1
482    1
483    1
484    1
485    1
486    1
487    1
488    1
490    0
491    0
492    0
493    0
494    0
495    0
496    0
497    0
498    0
499    0
501    0
502    0
503    0
504    0
505    0
506    0
507    0
508    0
509    0
510    0
511    0
512    0
513    0
514    0
516    0
517    0
518    0
519    0
521    0
522    0
523    1
524    1
525    1
526    1
527    1
528    1
529    1
530    1
531    1
532    1
533    1
534    1
535    1
536    1
537    1
538    1
540    1
541    1
542    1
543    1
544    1
545    1
546    1
547    0
548    0
549    0
550    0
551    0
552    0
553    0
554    0
555    0
556    0
557    0
558    0
559    0
560    0
561    0
562    0
563    0
564    0
565    0
566    0
567    0
568    0
569    0
570    0
571    0
572    0
573    0
574    0
575    0
576    0
577    0
578    0
579    0
580    0
581    0
582    0
583    0
584    0
585    0
586    0
587    0
588    0
589    0
590    0
591    0
593    0
594    0
595    0
596    0
597    0
599    0
600    0
602    1
603    1
604    1
605    1
606    0
607    1
609    1
610    1
611    1
612    1
613    1
614    1
615    1
616    1
617    1
618    1
619    1
620    1
621    0
623    1
624    1
625    1
627    1
628    1
629    1
630    1
631    1
632    1
633    1
634    1
635    1
636    1
637    1
638    1
639    1
640    1
642    1
643    1
644    1
645    1
646    1
647    1
648    1
649    1
650    1
651    1
652    1
653    1
654    1
655    1
656    1
657    1
658    1
659    1
660    1
661    1
662    1
663    1
664    1
665    1
666    1
667    1
668    1
669    1
670    1
671    1
672    1
674    1
675    1
676    1
677    1
678    1
679    1
680    1
681    1
682    1
683    1
684    1
685    1
686    1
687    1
688    1
689    1

In [26]:
(new_df_target['A16'] == 0).sum()

296

In [27]:
(new_df_target['A16'] == 1).sum()

357

### Performing the train test split for the training and testing dataset:

In [28]:
X_train, X_test, y_train, y_test = train_test_split(final, new_df_target, random_state=0)

### KNN

In [29]:
knn = KNeighborsClassifier(n_neighbors = 5)

In [30]:
knn.fit(X_train, y_train)

/Users/ayu/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier()

In [31]:
knn.score(X_test, y_test)

0.8292682926829268

In [32]:
y_pred = knn.predict(X_test)

In [33]:
confusion_matrix(y_test,y_pred)

array([[59, 16],
       [12, 77]])

In [34]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.79      0.81        75
           1       0.83      0.87      0.85        89

    accuracy                           0.83       164
   macro avg       0.83      0.83      0.83       164
weighted avg       0.83      0.83      0.83       164

In [35]:
pd.crosstab(np.array(y_test.values.tolist()).reshape((-1,)), y_pred, rownames=['True'], colnames=['Predicted'])

Predicted   0   1
True
0          59  16
1          12  77

In [36]:
np.array(y_test.values.tolist()).reshape((-1,))

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1])

### Logistic Regression

In [37]:
model = LogisticRegression(solver='liblinear', random_state=0)
model = LogisticRegression(solver='liblinear', random_state=0).fit(X_train, y_train)

/Users/ayu/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [38]:
model.score(X_test, y_test)

0.8963414634146342

In [39]:
y_pred=model.predict(X_test)

In [40]:
confusion_matrix(y_test,y_pred)

array([[70,  5],
       [12, 77]])

In [41]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.93      0.89        75
           1       0.94      0.87      0.90        89

    accuracy                           0.90       164
   macro avg       0.90      0.90      0.90       164
weighted avg       0.90      0.90      0.90       164

### SVM

In [42]:
svclassifier = SVC(kernel='linear')

In [43]:
svclassifier.fit(X_train, y_train)

/Users/ayu/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(kernel='linear')

In [44]:
y_pred = svclassifier.predict(X_test)

In [45]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[72  3]
 [15 74]]
              precision    recall  f1-score   support

           0       0.83      0.96      0.89        75
           1       0.96      0.83      0.89        89

    accuracy                           0.89       164
   macro avg       0.89      0.90      0.89       164
weighted avg       0.90      0.89      0.89       164